[versions]
agp = "8.13.2"
kotlin = "2.3.21"
compose = "2025.04.01"
activity = "1.10.1"
lifecycle = "2.8.7"
coroutines = "1.9.0"
serialization = "1.8.0"
okhttp = "4.12.0"
jose4j = "0.9.6"
junit = "4.13.2"
androidJunit = "1.2.1"
runner = "1.6.2"
jsr305 = "3.0.2"
orcex = "0.5.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-test = { module = "androidx.compose.ui:ui-test-junit4" }
compose-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
jose4j = { module = "org.bitbucket.b_c:jose4j", version.ref = "jose4j" }
junit = { module = "junit:junit", version.ref = "junit" }
android-junit = { module = "androidx.test.ext:junit", version.ref = "androidJunit" }
android-runner = { module = "androidx.test:runner", version.ref = "runner" }
jsr305 = { module = "com.google.code.findbugs:jsr305", version.ref = "jsr305" }
orcex-android = { module = "ru.wertik.orcex:orcex-render-android", version.ref = "orcex" }
orcex-font = { module = "ru.wertik.orcex:orcex-font-stix2-android", version.ref = "orcex" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
