// SPDX-License-Identifier: GPL-3.0-only
package io.github.xiaomeng2568.meldwise

import io.github.xiaomeng2568.meldwise.data.*
import io.github.xiaomeng2568.meldwise.provider.*
import io.github.xiaomeng2568.meldwise.security.*
import io.github.xiaomeng2568.meldwise.ui.*
import io.github.xiaomeng2568.meldwise.ui.presentation.*
import kotlinx.coroutines.*
import kotlinx.coroutines.test.*
import org.junit.Assert.*
import org.junit.Test
import java.io.File
import kotlinx.serialization.json.*

/** Same coordinator delegated by MainViewModel, real encrypted repository + scripted 7B executor.
 * No AppContainer, startup refresh, account, Android lifecycle, HTTP or device is involved.
 */
@OptIn(ExperimentalCoroutinesApi::class)
class DebateWorkflowTests {
    private class Fixture(val scope:TestScope,val config:DebateConfig=DebateFixtures.config) {
        val h=DebateHarness(scope,config)
        var busy=false;var error:String?=null;var settled=0
        val observed=mutableListOf<Conversation>()
        var catalogs=listOf(config.modelA,config.modelB,config.judge).distinctBy {it.ref}.groupBy {it.ref.providerId}.mapValues {(_,models)->
            models.map {LlmModel(it.ref.modelId,it.displayName ?: it.ref.modelId,"synthetic",ProviderCapability(emptySet()))}}
        val workflow=DebateWorkflow(scope,h.repository,h.registry,{catalogs},{busy},{busy=it},{error=it},
            {if(it!=null) observed.add(it)},{settled++},StandardTestDispatcher(scope.testScheduler),{h.executor()})
        init {workflow.restore(config);scope.runCurrent()}
        fun send(allow:Boolean=true,text:String="question") {
            workflow.send(text);scope.runCurrent()
            if(allow && workflow.state.value.sharingProviders!=null) {workflow.continueSharing();scope.runCurrent()}
        }
        fun automatic() {h.automatic={it.complete()}}
        fun complete() {h.finishAll()}
    }
    @Test fun newDebateCreatesOnlyDraft()=runTest {val f=Fixture(this);f.workflow.newDebate();runCurrent();assertEquals(ConversationMode.Debate,f.h.repository.mode());assertTrue(f.h.repository.sessions().isEmpty());assertNull(f.h.repository.activeConversation());assertNull(f.workflow.state.value.configured);assertTrue(f.h.calls.isEmpty())}
    @Test fun draftDoesNotDestroyExistingHistory()=runTest {val f=Fixture(this,DebateFixtures.same);f.automatic();f.send();val id=f.h.repository.conversationId();f.workflow.newDebate();runCurrent();assertEquals(listOf(id),f.h.repository.sessions().map {it.id});assertEquals(5,f.h.calls.size)}
    @Test fun chooseAChangesOnlyA()=runTest {val f=Fixture(this);val b=f.workflow.state.value.selection.b;val j=f.workflow.state.value.selection.judge;f.workflow.choose(DebateRole.A,f.config.judge.ref);runCurrent();assertEquals(b,f.workflow.state.value.selection.b);assertEquals(j,f.workflow.state.value.selection.judge);assertEquals(f.config.judge.ref,f.h.repository.debateConfig()!!.modelA.ref)}
    @Test fun chooseBChangesOnlyB()=runTest {val f=Fixture(this);f.workflow.choose(DebateRole.B,f.config.judge.ref);runCurrent();assertEquals(f.config.modelA,f.workflow.state.value.selection.a);assertEquals(f.config.judge.ref,f.h.repository.debateConfig()!!.modelB.ref)}
    @Test fun chooseJudgeChangesOnlyJudge()=runTest {val f=Fixture(this);f.workflow.choose(DebateRole.JUDGE,f.config.modelA.ref);runCurrent();assertEquals(f.config.modelA,f.workflow.state.value.selection.a);assertEquals(f.config.modelB,f.workflow.state.value.selection.b);assertEquals(f.config.modelA.ref,f.h.repository.debateConfig()!!.judge.ref)}
    @Test fun selectedRoleReasoningPersistsExactly()=runTest {val f=Fixture(this);f.workflow.thinking(DebateRole.JUDGE,ReasoningPreference.Max);runCurrent();assertEquals(ReasoningPreference.Max,f.h.repository.debateConfig()!!.judge.preference);assertEquals(f.config.modelA.preference,f.h.repository.debateConfig()!!.modelA.preference)}
    @Test fun unsupportedChatGptReasoningDoesNotMutate()=runTest {val f=Fixture(this);f.workflow.thinking(DebateRole.B,ReasoningPreference.Max);runCurrent();assertEquals(f.config,f.h.repository.debateConfig());assertTrue(f.h.calls.isEmpty())}
    @Test fun equalABDisablesSendWithoutOverwritingValidPersistedConfig()=runTest {val f=Fixture(this);f.workflow.choose(DebateRole.B,f.config.modelA.ref);runCurrent();assertFalse(f.workflow.state.value.sendReady);assertEquals(f.config,f.h.repository.debateConfig());f.send();assertTrue(f.h.calls.isEmpty());assertTrue(f.h.repository.sessions().isEmpty())}
    @Test fun judgeEqualAIsAdmitted()=runTest {val f=Fixture(this);f.workflow.choose(DebateRole.JUDGE,f.config.modelA.ref);runCurrent();assertTrue(f.workflow.state.value.sendReady);assertEquals(f.config.modelA.ref,f.h.repository.prepareDebate("q").config.judge.ref)}
    @Test fun judgeEqualBIsAdmitted()=runTest {val f=Fixture(this);f.workflow.choose(DebateRole.JUDGE,f.config.modelB.ref);runCurrent();assertTrue(f.workflow.state.value.sendReady);assertEquals(f.config.modelB.ref,f.h.repository.prepareDebate("q").config.judge.ref)}
    @Test fun unknownSelectionIsIgnored()=runTest {val f=Fixture(this);f.workflow.choose(DebateRole.JUDGE,ModelRef("deepseek","not-cached"));runCurrent();assertEquals(f.config,f.h.repository.debateConfig())}
    @Test fun missingJudgeCredentialsDisableSend()=runTest {val f=Fixture(this);f.h.readiness={ref,_->ref.providerId!="deepseek"};f.workflow.refreshAvailability();runCurrent();assertFalse(f.workflow.state.value.sendReady);f.send();assertTrue(f.h.calls.isEmpty());assertTrue(f.h.repository.sessions().isEmpty())}
    @Test fun unavailableCachedModelDisablesSend()=runTest {val f=Fixture(this);f.catalogs=f.catalogs.mapValues {(_,models)->models.map {it.copy(availability=ModelAvailability.UNAVAILABLE)}};f.workflow.refreshAvailability();runCurrent();assertFalse(f.workflow.state.value.sendReady);f.send();assertTrue(f.h.calls.isEmpty())}
    @Test fun emptyInputCannotSend()=runTest {val f=Fixture(this);f.send(text="  \n");assertTrue(f.h.calls.isEmpty());assertNull(f.h.repository.activeConversation())}
    @Test fun sharingRequirementExposesActualProviderNamesBeforeAdmission()=runTest {val f=Fixture(this);f.send(false);assertEquals(setOf("chatgpt","deepseek"),f.workflow.state.value.sharingProviders);assertFalse(f.busy);assertTrue(f.h.calls.isEmpty());assertNull(f.h.repository.activeConversation())}
    @Test fun cancellingConfirmationDoesNotAdmitOrGrant()=runTest {val f=Fixture(this);val before=f.h.blob.read();f.send(false);f.workflow.dismissSharing();runCurrent();assertArrayEquals(before,f.h.blob.read());assertTrue(f.h.calls.isEmpty());assertNull(f.h.repository.activeConversation());assertNull(f.workflow.state.value.sharingProviders)}
    @Test fun continueExecutesExactlyOnceEvenRepeatedTap()=runTest {val f=Fixture(this);f.automatic();f.send(false);f.workflow.continueSharing();f.workflow.continueSharing();runCurrent();assertEquals(5,f.h.calls.size);assertEquals(1,f.h.repository.activeConversation()!!.debateRounds.size);assertEquals(setOf("chatgpt|deepseek"),f.h.repository.activeConversation()!!.debateGrants);assertFalse(f.busy)}
    @Test fun sameProviderStartsWithoutDialog()=runTest {val f=Fixture(this,DebateFixtures.same);f.automatic();f.send(false);assertNull(f.workflow.state.value.sharingProviders);assertEquals(5,f.h.calls.size);assertEquals(DebateRoundState.Complete,f.h.round().lifecycle)}
    @Test fun busySendCannotDuplicateAttempt()=runTest {val f=Fixture(this);f.send();f.workflow.send("duplicate");runCurrent();assertEquals(2,f.h.calls.size);assertEquals(1,f.h.repository.activeConversation()!!.debateRounds.size);f.workflow.cancel();runCurrent()}
    @Test fun liveInitialSiblingUpdatesAreForwardedIndependently()=runTest {val f=Fixture(this);f.send();f.h.call(DebateStageType.INITIAL_A).complete("A visible");runCurrent();val r=f.observed.last().debateRounds.last();assertEquals("A visible",r.stage(DebateStageType.INITIAL_A).output);assertEquals(DebateStageState.Running,r.stage(DebateStageType.INITIAL_B).state);f.workflow.cancel();runCurrent()}
    @Test fun liveReviewWaveShowsBothRunning()=runTest {val f=Fixture(this);f.send();f.h.toReviews();val r=f.observed.last().debateRounds.last();assertEquals(DebateStageState.Running,r.stage(DebateStageType.REVIEW_A_OF_B).state);assertEquals(DebateStageState.Running,r.stage(DebateStageType.REVIEW_B_OF_A).state);f.workflow.cancel();runCurrent()}
    @Test fun cancellationStopsBothInitialTransports()=runTest {val f=Fixture(this);f.send();f.workflow.cancel();runCurrent();assertFalse(f.busy);assertEquals(DebateRoundState.Cancelled,f.h.round().lifecycle);assertEquals(2,f.h.calls.size);assertTrue(f.h.calls.all {it.closed.isCompleted})}
    @Test fun cancellationPreservesCompletedInitialSibling()=runTest {val f=Fixture(this);f.send();f.h.call(DebateStageType.INITIAL_A).complete("kept");runCurrent();f.workflow.cancel();runCurrent();assertEquals("kept",f.h.round().stage(DebateStageType.INITIAL_A).output);assertEquals(DebateStageState.Complete,f.h.round().stage(DebateStageType.INITIAL_A).state);assertEquals(2,f.h.calls.size)}
    @Test fun cancellationDuringReviewStopsJudge()=runTest {val f=Fixture(this);f.send();f.h.toReviews();f.workflow.cancel();runCurrent();assertEquals(4,f.h.calls.size);assertEquals(DebateStageState.NotRun,f.h.round().stage(DebateStageType.JUDGE).state)}
    @Test fun cancellationDuringJudgePreservesAllUpstream()=runTest {val f=Fixture(this);f.send();f.h.toJudge();f.workflow.cancel();runCurrent();assertTrue(f.h.round().stages.take(4).all {it.state==DebateStageState.Complete});assertEquals(DebateStageState.Cancelled,f.h.round().stage(DebateStageType.JUDGE).state)}
    @Test fun configurationCannotChangeDuringExecution()=runTest {val f=Fixture(this);f.send();f.workflow.choose(DebateRole.JUDGE,f.config.modelA.ref);f.workflow.thinking(DebateRole.A,ReasoningPreference.Max);runCurrent();assertEquals(f.config,f.h.round().config);assertEquals(f.config,f.h.repository.debateConfig());f.workflow.cancel();runCurrent()}
    @Test fun failedStageOwnsSafeErrorNotDuplicatedGlobally()=runTest {val f=Fixture(this);f.send();f.h.call(DebateStageType.INITIAL_B).fail(ErrorKind.PLAN_USAGE_LIMIT);runCurrent();assertEquals(ErrorKind.PLAN_USAGE_LIMIT,f.h.round().stage(DebateStageType.INITIAL_B).error);assertNull(f.error);assertEquals(2,f.h.calls.size);assertFalse(f.busy)}
    @Test fun wholeRoundRetryUsesOriginalModelsEvenAfterCurrentConfigChanges()=runTest {val f=Fixture(this);f.send();f.h.call(DebateStageType.INITIAL_B).fail(ErrorKind.NETWORK);runCurrent();val old=f.h.round();f.workflow.choose(DebateRole.JUDGE,f.config.modelA.ref);runCurrent();f.automatic();f.workflow.retry(old.roundId);runCurrent();assertEquals(7,f.h.calls.size);val rounds=f.h.repository.activeConversation()!!.debateRounds;assertEquals(old,rounds.first());assertEquals(old.config,rounds.last().config);assertEquals(old.roundId,rounds.last().retryOf);assertEquals(old.frozenInput,rounds.last().frozenInput)}
    @Test fun grantedRetryDoesNotAskAgain()=runTest {val f=Fixture(this);f.send();f.h.call(DebateStageType.INITIAL_A).fail(ErrorKind.NETWORK);runCurrent();val id=f.h.round().roundId;f.automatic();f.workflow.retry(id);runCurrent();assertNull(f.workflow.state.value.sharingProviders);assertEquals(7,f.h.calls.size)}
    @Test fun cancelledRoundRetryStartsFiveNewStagesNotUnfinishedOnly()=runTest {val f=Fixture(this);f.send();f.workflow.cancel();runCurrent();val id=f.h.round().roundId;f.automatic();f.workflow.retry(id);runCurrent();assertEquals(7,f.h.calls.size);assertEquals(2,f.h.repository.activeConversation()!!.debateRounds.size);assertEquals(DebateRoundState.Complete,f.h.round().lifecycle)}
    @Test fun reopeningHistoryNeverExecutes()=runTest {val f=Fixture(this);f.automatic();f.send();val id=f.h.repository.conversationId();val calls=f.h.calls.size;f.h.repository.activateSession(id);f.workflow.restore(f.h.repository.debateConfig());runCurrent();assertEquals(calls,f.h.calls.size);assertEquals(f.config,f.workflow.state.value.configured);assertEquals(1,f.h.repository.sessions().size)}
    @Test fun interruptedHistoryRestoresWithoutSpinnerOrReplay()=runTest {val f=Fixture(this);f.send();val restored=ChatRepository(f.h.blob,f.h.box);restored.load();val r=restored.activeConversation()!!.debateRounds.last();assertEquals(DebateRoundState.Interrupted,r.lifecycle);assertTrue(debateRetryEligible(restored.activeConversation()!!,r));assertEquals(2,f.h.calls.size);f.workflow.cancel();runCurrent()}
    @Test fun followUpIsSecondRoundInSameConversation()=runTest {val f=Fixture(this);f.automatic();f.send();val id=f.h.repository.conversationId();f.send(text="follow up");assertEquals(10,f.h.calls.size);assertEquals(id,f.h.repository.conversationId());assertEquals(1,f.h.repository.sessions().size);assertEquals(2,f.h.repository.activeConversation()!!.debateRounds.size)}
    @Test fun followUpProviderInputUsesOnlyPreviousUserAndJudgeContext()=runTest {val f=Fixture(this);f.automatic();f.send();f.send(text="follow up");val texts=f.h.calls[5].request.messages.map {it.text};assertTrue(texts.contains("question"));assertTrue(texts.contains("visible-JUDGE"));assertFalse(texts.any {it.contains("visible-INITIAL") || it.contains("visible-REVIEW")})}
    @Test fun changedProviderSetWithRetainedCrossProviderContextRequiresConfirmationAgain()=runTest {val f=Fixture(this);f.automatic();f.send();val next=ModelRef("chatgpt","another");f.catalogs=f.catalogs+("chatgpt" to (f.catalogs.getValue("chatgpt")+LlmModel(next.modelId,"Another","synthetic",ProviderCapability(emptySet()))));f.workflow.choose(DebateRole.A,next);runCurrent();f.workflow.choose(DebateRole.JUDGE,f.config.modelB.ref);runCurrent();f.send(false,text="changed set");assertNotNull(f.workflow.state.value.sharingProviders);assertEquals(5,f.h.calls.size);assertEquals(1,f.h.repository.activeConversation()!!.debateRounds.size)}
    @Test fun discardedIntermediateProviderDoesNotCreateFalseSharingWarning()=runTest {val f=Fixture(this);f.automatic();f.send();f.workflow.choose(DebateRole.B,f.config.judge.ref);runCurrent();f.send(false,text="only retained provider");assertNull(f.workflow.state.value.sharingProviders);assertEquals(10,f.h.calls.size)}
    @Test fun sameProviderSetDifferentJudgeDoesNotPromptAgain()=runTest {val f=Fixture(this);f.automatic();f.send();f.workflow.choose(DebateRole.JUDGE,f.config.modelB.ref);runCurrent();f.send(false,text="same set");assertNull(f.workflow.state.value.sharingProviders);assertEquals(10,f.h.calls.size)}
    @Test fun staleConsentIsDiscardedWhenConfigurationChanges()=runTest {val f=Fixture(this);f.send(false);f.workflow.choose(DebateRole.JUDGE,f.config.modelA.ref);runCurrent();f.workflow.continueSharing();runCurrent();assertTrue(f.h.calls.isEmpty());assertNull(f.workflow.state.value.sharingProviders)}
    @Test fun credentialRemovalWhileConfirmationIsOpenPreventsAdmission()=runTest {val f=Fixture(this);f.send(false);f.h.readiness={_,_->false};f.workflow.continueSharing();runCurrent();assertEquals("MODEL_UNAVAILABLE",f.error);assertTrue(f.h.calls.isEmpty());assertNull(f.h.repository.activeConversation());assertFalse(f.workflow.state.value.sendReady)}
    @Test fun cachedModelRemovalWhileConfirmationIsOpenPreventsAdmission()=runTest {val f=Fixture(this);f.send(false);f.catalogs=emptyMap();f.workflow.continueSharing();runCurrent();assertTrue(f.h.calls.isEmpty());assertNull(f.h.repository.activeConversation());assertEquals("MODEL_UNAVAILABLE",f.error)}
    @Test fun retryWithAbsentGrantRequiresExplicitConsentAgain()=runTest {
        val f=Fixture(this);f.send();f.h.call(DebateStageType.INITIAL_B).fail(ErrorKind.NETWORK);runCurrent();val old=f.h.round()
        val root=Json.parseToJsonElement(f.h.box.open(f.h.blob.read()!!).decodeToString()).jsonObject
        val conversations=root.getValue("conversations").jsonArray.map {JsonObject(it.jsonObject+("debateGrants" to JsonArray(emptyList())))}
        f.h.blob.write(f.h.box.seal(JsonObject(root+("conversations" to JsonArray(conversations))).toString().toByteArray()))
        val restored=ChatRepository(f.h.blob,f.h.box);restored.load();var busy=false
        val workflow=DebateWorkflow(this,restored,f.h.registry,{f.catalogs},{busy},{busy=it},{fail(it)},{},{},StandardTestDispatcher(testScheduler),
            {DebateExecutor(f.h.registry,restored,persistenceDispatcher=StandardTestDispatcher(testScheduler))})
        workflow.restore(restored.debateConfig());runCurrent();workflow.retry(old.roundId);runCurrent()
        assertEquals(setOf("deepseek","chatgpt"),workflow.state.value.sharingProviders);assertEquals(2,f.h.calls.size)
        assertEquals(1,restored.activeConversation()!!.debateRounds.size);workflow.dismissSharing();assertTrue(restored.activeConversation()!!.debateGrants.isEmpty())
    }
    @Test fun restoredDebateCountsAndOrderingSurviveRestart()=runTest {val f=Fixture(this);f.automatic();f.send();val first=f.h.repository.conversationId();f.workflow.newDebate();runCurrent();f.workflow.restore(f.config);f.h.repository.configureDebate(f.config);runCurrent();f.send();val second=f.h.repository.conversationId();f.h.repository.moveSession(first,-1,ConversationMode.Debate);val r=ChatRepository(f.h.blob,f.h.box);r.load();assertEquals(listOf(first,second),historyEntries(HistoryCategory.Debate,r.sessions(),emptyList()).map {it.id});assertEquals(2,historySummaries(r.sessions(),emptyList()).last().count)}
    @Test fun deletingDebateDoesNotDeleteSingle()=runTest {val f=Fixture(this);f.automatic();f.send();val debateId=f.h.repository.conversationId();f.h.repository.newSession(f.config.modelA.ref);val output=f.h.repository.begin("single").first;f.h.repository.update(output,"answer",MessageState.COMPLETED);val singleId=f.h.repository.conversationId();f.h.repository.deleteSession(debateId);assertEquals(listOf(singleId),f.h.repository.sessions().map {it.id});assertEquals(ConversationMode.Single,f.h.repository.mode())}
    @Test fun viewModelDelegatesSendCancelRetryAndRestoreWithoutComposeExecution() {val root=File(System.getProperty("projectRoot"),"app/src/main/java/io/github/xiaomeng2568/meldwise/ui");val vm=File(root,"MainViewModel.kt").readText();assertTrue(vm.contains("debateWorkflow.send(text)"));assertTrue(vm.contains("debateWorkflow.cancel()"));assertTrue(vm.contains("debateWorkflow.retry(id)"));assertTrue(vm.contains("debateWorkflow.restore(container.chat.debateConfig())"));assertFalse(File(root,"ChatScreen.kt").readText().contains("DebateExecutor("));val open=vm.substringAfter("fun openSession(").substringBefore("fun startCompare(");assertFalse(open.contains("execute("));assertFalse(open.contains("send("))}
}
