// SPDX-License-Identifier: GPL-3.0-only
package io.github.xiaomeng2568.meldwise

import io.github.xiaomeng2568.meldwise.data.*
import io.github.xiaomeng2568.meldwise.provider.*
import io.github.xiaomeng2568.meldwise.security.*
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.*
import org.junit.Assert.*
import org.junit.Test

class DebatePersistenceTests {
    private val f=DebateFixtures
    private fun repo(blob:MemoryBlob=MemoryBlob(),box:AesGcmBox=testBox(),config:DebateConfig=f.same)=
        ChatRepository(blob,box,clock={10}).also {it.newDebate();it.configureDebate(config)}
    private fun begin(r:ChatRepository,text:String="question")=r.beginDebate(r.prepareDebate(text),true).debateRounds.last()
    private fun finish(r:ChatRepository,type:DebateStageType,output:String="visible-$type",error:ErrorKind?=null):Conversation {
        val id=r.activeConversation()!!.debateRounds.last().roundId
        val s=r.startDebateStage(id,type).debateRounds.last().stage(type)
        return r.updateDebateStage(id,s.copy(output=output,state=if(error==null) DebateStageState.Complete else DebateStageState.Failed,error=error,endedAt=10))
    }
    private fun complete(r:ChatRepository) {DebateStageType.entries.forEach {finish(r,it)}}
    @Test fun emptyDebateDraftNotInHistory() {val r=repo();assertTrue(r.sessions().isEmpty())}
    @Test fun beginPersistsFiveReservedStages() {val r=repo();val round=begin(r);assertEquals(5,round.stages.size);assertEquals(DebateRoundState.Pending,round.lifecycle);assertEquals(1,r.sessions().size)}
    @Test fun twoRoundsOneConversation() {val r=repo();begin(r);complete(r);val id=r.conversationId();begin(r,"follow-up");assertEquals(id,r.conversationId());assertEquals(1,r.sessions().size);assertEquals(2,r.activeConversation()!!.debateRounds.size)}
    @Test fun noProviderExecutorNeededForPersistence() {val r=repo();begin(r);assertTrue(r.activeConversation()!!.debateRounds.single().stages.all {it.state==DebateStageState.Pending})}
    @Test fun refusedConsentAppendsNothing() {val r=repo(config=f.config);val p=r.prepareDebate("q");assertTrue(p.requiresSharing);assertThrows(ContextSharingRequired::class.java) {r.beginDebate(p)};assertNull(r.activeConversation());assertTrue(r.sessions().isEmpty())}
    @Test fun consentGrantStoredOnlyOnAdmission() {val r=repo(config=f.config);r.prepareDebate("q");assertNull(r.activeConversation());begin(r);assertEquals(setOf("chatgpt|deepseek"),r.activeConversation()!!.debateGrants)}
    @Test fun grantSurvivesRestartConversationLocally() {val blob=MemoryBlob();val box=testBox();val r=repo(blob,box,f.config);begin(r);complete(r);val restored=ChatRepository(blob,box);assertFalse(restored.prepareDebate("next").requiresSharing);restored.newDebate();restored.configureDebate(f.config);assertTrue(restored.prepareDebate("new").requiresSharing)}
    @Test fun roleChangesWithSameSetDoNotReconfirm() {val r=repo(config=f.config);begin(r);complete(r);r.configureDebate(f.config.copy(modelA=f.b,modelB=f.a,judge=f.b));assertFalse(r.prepareDebate("next").requiresSharing)}
    @Test fun changedProviderSetRequiresNewGrant() {val r=repo(config=f.config.copy(judge=f.b));begin(r);complete(r);r.configureDebate(f.same);assertTrue(r.prepareDebate("next").requiresSharing);assertEquals(setOf("chatgpt|deepseek"),r.activeConversation()!!.debateGrants)}
    @Test fun expiredPlanRejected() {val r=repo();val p=r.prepareDebate("q");r.beginDebate(p);assertThrows(IllegalArgumentException::class.java) {r.beginDebate(p)}}
    @Test fun changedConfigInvalidatesPlan() {val r=repo();val p=r.prepareDebate("q");r.configureDebate(f.same.copy(judge=f.b));assertThrows(IllegalArgumentException::class.java) {r.beginDebate(p,true)}}
    @Test fun initialsCanBeStartedInEitherOrder() {val r=repo();val id=begin(r).roundId;r.startDebateStage(id,DebateStageType.INITIAL_B);r.startDebateStage(id,DebateStageType.INITIAL_A);assertEquals(2,r.activeConversation()!!.debateRounds.single().stages.count {it.state==DebateStageState.Running})}
    @Test fun reviewBeforeBothInitialsRejected() {val r=repo();val id=begin(r).roundId;finish(r,DebateStageType.INITIAL_A);assertThrows(IllegalArgumentException::class.java) {r.startDebateStage(id,DebateStageType.REVIEW_A_OF_B)}}
    @Test fun reviewsCanRunTogether() {val r=repo();val id=begin(r).roundId;finish(r,DebateStageType.INITIAL_B);finish(r,DebateStageType.INITIAL_A);r.startDebateStage(id,DebateStageType.REVIEW_B_OF_A);r.startDebateStage(id,DebateStageType.REVIEW_A_OF_B);assertEquals(2,r.activeConversation()!!.debateRounds.single().stages.count {it.state==DebateStageState.Running})}
    @Test fun judgeNeedsBothReviews() {val r=repo();val id=begin(r).roundId;DebateStageType.entries.take(3).forEach {finish(r,it)};assertThrows(IllegalArgumentException::class.java) {r.startDebateStage(id,DebateStageType.JUDGE)}}
    @Test fun completedRoundReopensWithoutReplay() {val blob=MemoryBlob();val box=testBox();val r=repo(blob,box);begin(r);complete(r);val before=blob.read();val restored=ChatRepository(blob,box);restored.load();assertArrayEquals(before,blob.read());assertEquals(DebateRoundState.Complete,restored.activeConversation()!!.debateRounds.single().lifecycle)}
    @Test fun restartInterruptsBothActiveInitials() {val blob=MemoryBlob();val box=testBox();val r=repo(blob,box);val id=begin(r).roundId;DebateStageType.entries.take(2).forEach {r.startDebateStage(id,it)};val reopened=ChatRepository(blob,box);reopened.load();assertEquals(2,reopened.activeConversation()!!.debateRounds.single().stages.count {it.state==DebateStageState.Interrupted})}
    @Test fun recoverySecondLoadDoesNotRewrite() {val blob=MemoryBlob();val box=testBox();val r=repo(blob,box);begin(r);val restored=ChatRepository(blob,box);restored.load();val bytes=blob.read();ChatRepository(blob,box).load();assertArrayEquals(bytes,blob.read())}
    @Test fun cancelRoundKeepsPreviousRounds() {val r=repo();begin(r);complete(r);val old=Json.encodeToString(r.activeConversation()!!.debateRounds.single());val id=begin(r,"next").roundId;r.startDebateStage(id,DebateStageType.INITIAL_B);r.cancelDebateRound(id);assertEquals(old,Json.encodeToString(r.activeConversation()!!.debateRounds.first()));assertEquals(DebateRoundState.Cancelled,r.activeConversation()!!.debateRounds.last().lifecycle)}
    @Test fun cancelUnstartedRoundHasNoRunnableStage() {val r=repo();val id=begin(r).roundId;val c=r.cancelDebateRound(id);assertEquals(DebateRoundState.Cancelled,c.debateRounds.single().lifecycle);assertTrue(DebateDag.readyStages(c.debateRounds.single()).isEmpty())}
    @Test fun cancelReviewPreservesBothInitials() {val r=repo();val id=begin(r).roundId;DebateStageType.entries.take(2).forEach {finish(r,it)};r.startDebateStage(id,DebateStageType.REVIEW_A_OF_B);val round=r.cancelDebateRound(id).debateRounds.single();assertEquals(2,round.stages.count {it.state==DebateStageState.Complete});assertEquals(DebateStageState.NotRun,round.stage(DebateStageType.JUDGE).state)}
    @Test fun cancelJudgePreservesAllUpstreamOutputs() {val r=repo();val id=begin(r).roundId;DebateStageType.entries.take(4).forEach {finish(r,it)};r.startDebateStage(id,DebateStageType.JUDGE);val round=r.cancelDebateRound(id).debateRounds.single();assertEquals(4,round.stages.count {it.state==DebateStageState.Complete});assertEquals(DebateStageState.Cancelled,round.stage(DebateStageType.JUDGE).state)}
    @Test fun usageLimitPreservesSiblingNoFallback() {val r=repo();begin(r);finish(r,DebateStageType.INITIAL_B);val c=finish(r,DebateStageType.INITIAL_A,error=ErrorKind.PLAN_USAGE_LIMIT);assertEquals(ErrorKind.PLAN_USAGE_LIMIT,c.debateRounds.single().stage(DebateStageType.INITIAL_A).error);assertEquals(DebateStageState.Complete,c.debateRounds.single().stage(DebateStageType.INITIAL_B).state);assertEquals(f.same,c.debateRounds.single().config)}
    @Test fun updateCannotRelabelSnapshot() {val r=repo();val id=begin(r).roundId;val s=r.startDebateStage(id,DebateStageType.INITIAL_A).debateRounds.single().stage(DebateStageType.INITIAL_A);assertThrows(IllegalArgumentException::class.java) {r.updateDebateStage(id,s.copy(model=f.judge))}}
    @Test fun emptySuccessfulOutputRejectedAtomically() {val blob=MemoryBlob();val r=repo(blob);val id=begin(r).roundId;val s=r.startDebateStage(id,DebateStageType.INITIAL_A).debateRounds.single().stage(DebateStageType.INITIAL_A);val before=blob.read();assertThrows(IllegalArgumentException::class.java) {r.updateDebateStage(id,s.copy(state=DebateStageState.Complete))};assertArrayEquals(before,blob.read())}
    @Test fun retryUsesOriginalConfigAndFrozenInput() {val r=repo();begin(r);finish(r,DebateStageType.INITIAL_A,error=ErrorKind.PROTOCOL);val old=r.activeConversation()!!.debateRounds.single();r.configureDebate(f.config);val p=r.prepareDebateRetry(old.roundId);assertEquals(old.config,p.config);assertEquals(old.frozenInput.map {it.text},p.context.messages.map {it.text});assertEquals(old.roundId,p.retryOf);val next=r.beginDebate(p,true).debateRounds.last();assertEquals(old.config,next.config);assertEquals(old.frozenInput,next.frozenInput);assertEquals(old.sourceProviders,next.sourceProviders)}
    @Test fun successfulRoundCannotBeRetried() {val r=repo();val id=begin(r).roundId;complete(r);assertThrows(IllegalArgumentException::class.java) {r.prepareDebateRetry(id)}}
    @Test fun runningRoundCannotBeRetried() {val r=repo();val id=begin(r).roundId;assertThrows(IllegalArgumentException::class.java) {r.prepareDebateRetry(id)}}
    @Test fun retryLinkPersistsAcrossRestart() {val blob=MemoryBlob();val box=testBox();val r=repo(blob,box);val id=begin(r).roundId;r.cancelDebateRound(id);r.beginDebate(r.prepareDebateRetry(id),true);val reopened=ChatRepository(blob,box);reopened.load();assertEquals(id,reopened.activeConversation()!!.debateRounds.last().retryOf)}
    @Test fun retryKeepsOriginalInputRevision() {val r=repo();val original=begin(r);r.cancelDebateRound(original.roundId);r.configureDebate(f.config);val plan=r.prepareDebateRetry(original.roundId);val retry=r.beginDebate(plan,true).debateRounds.last();assertEquals(original.inputRevision,retry.inputRevision)}
    @Test fun storedRetryCannotChangeOriginalConfig() {val original=settleDebateRound(f.change(f.round(),DebateStageType.INITIAL_A,DebateStageState.Failed),11);val retry=f.round(config=f.same).copy(roundId="retry",userMessageId="retry-user",retryOf=original.roundId,stages=f.round(config=f.same).stages.map {it.copy(stageId="retry-${it.type}")});val c=f.conversation(original).let {it.copy(messages=it.messages+ChatMessage("retry-user","user",MessageRole.USER,"CURRENT_QUESTION",MessageState.COMPLETED,order=1),debateRounds=listOf(original,retry))};assertThrows(IllegalArgumentException::class.java) {validateDebate(c)}}
    @Test fun laterConfigDoesNotMutateOldStagePreferences() {val r=repo();begin(r);complete(r);val old=r.activeConversation()!!.debateRounds.single();r.configureDebate(f.same.copy(modelA=f.a.copy(preference=ReasoningPreference.Off)));assertEquals(ReasoningPreference.High,old.stage(DebateStageType.INITIAL_A).model.preference)}
    @Test fun titleStaysFirstQuestion() {val r=repo();begin(r,"first");complete(r);begin(r,"second");assertEquals("first",r.sessions().single().title)}
    @Test fun deleteActiveDebateLeavesSafeSingleDraft() {val r=repo();begin(r);r.deleteSession(r.conversationId());assertEquals(ConversationMode.Single,r.mode());assertNull(r.activeConversation());assertTrue(r.sessions().isEmpty())}
    @Test fun reorderDebateKeepsExistingCategoryOrder() {val r=repo();begin(r,"first");complete(r);val first=r.conversationId();r.newDebate();r.configureDebate(f.same);begin(r,"second");r.moveSession(first,-1,ConversationMode.Debate);assertEquals(first,r.sessions().first().id);r.activateSession(first);assertEquals(ConversationMode.Debate,r.mode());assertEquals(2,r.sessions().size)}
    @Test fun thirtyThreeRoundsConsume198Records() {val r=repo();repeat(33) {val round=begin(r,"q$it");r.cancelDebateRound(round.roundId)};assertEquals(33,r.activeConversation()!!.debateRounds.size);assertThrows(IllegalArgumentException::class.java) {begin(r,"overflow")}}
    @Test fun exact200AdmissionReservesSix() {val r=repo();r.newSession(f.a.ref);repeat(97) {val id=r.begin("single$it").first;r.update(id,"a",MessageState.COMPLETED)};r.newDebate();r.configureDebate(f.same);val round=begin(r);assertEquals(5,round.stages.size);r.cancelDebateRound(round.roundId);assertThrows(IllegalArgumentException::class.java) {begin(r,"overflow")};assertEquals(2,r.sessions().size)}
    @Test fun recordOverflowPreservesCiphertext() {val blob=MemoryBlob();val r=repo(blob);repeat(33) {val round=begin(r);r.cancelDebateRound(round.roundId)};val old=blob.read();assertThrows(IllegalArgumentException::class.java) {begin(r)};assertArrayEquals(old,blob.read())}
    @Test fun conversationLimitStill32() {val r=repo();repeat(32) {r.newDebate();r.configureDebate(f.same);begin(r);r.cancelDebateRound(r.activeConversation()!!.debateRounds.last().roundId)};r.newDebate();r.configureDebate(f.same);assertThrows(IllegalArgumentException::class.java) {begin(r)};assertEquals(32,r.sessions().size)}
    @Test fun snapshotsAreEncrypted() {val blob=MemoryBlob();val r=repo(blob);begin(r,"SYNTHETIC_PRIVATE_USER");assertFalse(String(blob.read()!!,Charsets.ISO_8859_1).contains("SYNTHETIC_PRIVATE_USER"))}
    @Test fun noSingleSendInDebateMode() {val r=repo();assertThrows(IllegalArgumentException::class.java) {r.begin("not executed")}}
    @Test fun noCollaborateSendInDebateMode() {val r=repo();assertThrows(IllegalArgumentException::class.java) {r.prepareCollaborate("not executed")}}
    @Test fun debounceStageDuplicateStartRejected() {val r=repo();val id=begin(r).roundId;r.startDebateStage(id,DebateStageType.INITIAL_A);assertThrows(IllegalArgumentException::class.java) {r.startDebateStage(id,DebateStageType.INITIAL_A)}}
    @Test fun persistedDebateUsesRealHistoryCategoryIn7C() {val r=repo();begin(r);assertTrue(io.github.xiaomeng2568.meldwise.ui.presentation.HistoryCategory.Debate.available);assertEquals(1,io.github.xiaomeng2568.meldwise.ui.presentation.historyEntries(io.github.xiaomeng2568.meldwise.ui.presentation.HistoryCategory.Debate,r.sessions(),emptyList()).size)}
}
